services:
  - type: web
    name: auchan-scraper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m playwright install --with-deps chromium
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
  - key: auchan_username
    fromSecret: auchan_username
  - key: auchan_password
    fromSecret: auchan_password
