services:
  - type: web
    name: rapthor
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
