services:
  - type: web
    name: auchan-scraper
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: auchan_username
        fromSecret: auchan_username
      - key: auchan_password
        fromSecret: auchan_password
